# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/optimization_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_optimization_dialog(object):
    def setupUi(self, optimization_dialog):
        optimization_dialog.setObjectName("optimization_dialog")
        optimization_dialog.resize(360, 306)
        optimization_dialog.setMinimumSize(QtCore.QSize(360, 306))
        optimization_dialog.setBaseSize(QtCore.QSize(360, 306))
        optimization_dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(optimization_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(optimization_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 13, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.optimization_label = QtWidgets.QLabel(optimization_dialog)
        self.optimization_label.setObjectName("optimization_label")
        self.verticalLayout.addWidget(self.optimization_label)
        self.marker1_radio = QtWidgets.QRadioButton(optimization_dialog)
        self.marker1_radio.setChecked(True)
        self.marker1_radio.setObjectName("marker1_radio")
        self.verticalLayout.addWidget(self.marker1_radio)
        self.marker2_radio = QtWidgets.QRadioButton(optimization_dialog)
        self.marker2_radio.setObjectName("marker2_radio")
        self.verticalLayout.addWidget(self.marker2_radio)
        self.gridLayout.addLayout(self.verticalLayout, 4, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.options_label = QtWidgets.QLabel(optimization_dialog)
        self.options_label.setObjectName("options_label")
        self.verticalLayout_2.addWidget(self.options_label)
        self.ignore_intermediary_markers_checkbox = QtWidgets.QCheckBox(optimization_dialog)
        self.ignore_intermediary_markers_checkbox.setChecked(True)
        self.ignore_intermediary_markers_checkbox.setObjectName("ignore_intermediary_markers_checkbox")
        self.verticalLayout_2.addWidget(self.ignore_intermediary_markers_checkbox)
        self.gridLayout.addLayout(self.verticalLayout_2, 8, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(optimization_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cost_function_label = QtWidgets.QLabel(optimization_dialog)
        self.cost_function_label.setObjectName("cost_function_label")
        self.gridLayout_2.addWidget(self.cost_function_label, 1, 0, 1, 1)
        self.cost_func_combo = QtWidgets.QComboBox(optimization_dialog)
        self.cost_func_combo.setObjectName("cost_func_combo")
        self.gridLayout_2.addWidget(self.cost_func_combo, 1, 1, 1, 1)
        self.algorithm_combo = QtWidgets.QComboBox(optimization_dialog)
        self.algorithm_combo.setObjectName("algorithm_combo")
        self.gridLayout_2.addWidget(self.algorithm_combo, 0, 1, 1, 1)
        self.algorithm_label = QtWidgets.QLabel(optimization_dialog)
        self.algorithm_label.setObjectName("algorithm_label")
        self.gridLayout_2.addWidget(self.algorithm_label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(optimization_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)

        self.retranslateUi(optimization_dialog)
        self.buttonBox.accepted.connect(optimization_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(optimization_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(optimization_dialog)

    def retranslateUi(self, optimization_dialog):
        _translate = QtCore.QCoreApplication.translate
        optimization_dialog.setWindowTitle(_translate("optimization_dialog", "Optimize Route"))
        self.optimization_label.setText(_translate("optimization_dialog", "Start Optimization From:"))
        self.marker1_radio.setText(_translate("optimization_dialog", "Marker 1"))
        self.marker2_radio.setText(_translate("optimization_dialog", "Marker 2"))
        self.options_label.setText(_translate("optimization_dialog", "Additional Options:"))
        self.ignore_intermediary_markers_checkbox.setText(_translate("optimization_dialog", "Ignore Intermediary Markers"))
        self.cost_function_label.setText(_translate("optimization_dialog", "Cost Function:"))
        self.algorithm_label.setText(_translate("optimization_dialog", "Algorithm:"))
