# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/set_time_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_timer_dialog(object):
    def setupUi(self, timer_dialog):
        timer_dialog.setObjectName("timer_dialog")
        timer_dialog.resize(340, 240)
        timer_dialog.setMinimumSize(QtCore.QSize(340, 240))
        timer_dialog.setBaseSize(QtCore.QSize(340, 240))
        timer_dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(timer_dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.seconds_label = QtWidgets.QLabel(timer_dialog)
        self.seconds_label.setObjectName("seconds_label")
        self.gridLayout_2.addWidget(self.seconds_label, 1, 0, 1, 1)
        self.minutes_label = QtWidgets.QLabel(timer_dialog)
        self.minutes_label.setObjectName("minutes_label")
        self.gridLayout_2.addWidget(self.minutes_label, 0, 0, 1, 1)
        self.minutes_edit = QtWidgets.QLineEdit(timer_dialog)
        self.minutes_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minutes_edit.setObjectName("minutes_edit")
        self.gridLayout_2.addWidget(self.minutes_edit, 0, 1, 1, 1)
        self.seconds_edit = QtWidgets.QLineEdit(timer_dialog)
        self.seconds_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seconds_edit.setObjectName("seconds_edit")
        self.gridLayout_2.addWidget(self.seconds_edit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(timer_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)

        self.retranslateUi(timer_dialog)
        self.buttonBox.accepted.connect(timer_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(timer_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(timer_dialog)

    def retranslateUi(self, timer_dialog):
        _translate = QtCore.QCoreApplication.translate
        timer_dialog.setWindowTitle(_translate("timer_dialog", "Set Time"))
        self.seconds_label.setText(_translate("timer_dialog", "Seconds:"))
        self.minutes_label.setText(_translate("timer_dialog", "Minutes:"))
        self.minutes_edit.setPlaceholderText(_translate("timer_dialog", "MM"))
        self.seconds_edit.setPlaceholderText(_translate("timer_dialog", "SS"))
