# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/antenna_control_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AntennaControl(object):
    def setupUi(self, AntennaControl):
        AntennaControl.setObjectName("AntennaControl")
        AntennaControl.resize(400, 58)
        self.gridLayout = QtWidgets.QGridLayout(AntennaControl)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(AntennaControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(AntennaControl)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(AntennaControl)
        QtCore.QMetaObject.connectSlotsByName(AntennaControl)

    def retranslateUi(self, AntennaControl):
        _translate = QtCore.QCoreApplication.translate
        AntennaControl.setWindowTitle(_translate("AntennaControl", "Antenna Control"))
        self.label.setText(_translate("AntennaControl", "Antenna Servo Position"))
