# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/checklist_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Checklist(object):
    def setupUi(self, Checklist):
        Checklist.setObjectName("Checklist")
        Checklist.resize(774, 576)
        self.gridLayout = QtWidgets.QGridLayout(Checklist)
        self.gridLayout.setObjectName("gridLayout")
        self.list_selection = QtWidgets.QComboBox(Checklist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_selection.sizePolicy().hasHeightForWidth())
        self.list_selection.setSizePolicy(sizePolicy)
        self.list_selection.setObjectName("list_selection")
        self.list_selection.addItem("")
        self.list_selection.setItemText(0, "")
        self.gridLayout.addWidget(self.list_selection, 0, 1, 1, 1)
        self.checklist_label = QtWidgets.QLabel(Checklist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checklist_label.sizePolicy().hasHeightForWidth())
        self.checklist_label.setSizePolicy(sizePolicy)
        self.checklist_label.setObjectName("checklist_label")
        self.gridLayout.addWidget(self.checklist_label, 0, 0, 1, 1)
        self.tree = QtWidgets.QTreeWidget(Checklist)
        self.tree.setObjectName("tree")
        self.tree.header().setVisible(False)
        self.gridLayout.addWidget(self.tree, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.expand_button = QtWidgets.QPushButton(Checklist)
        self.expand_button.setObjectName("expand_button")
        self.horizontalLayout.addWidget(self.expand_button)
        self.collapse_button = QtWidgets.QPushButton(Checklist)
        self.collapse_button.setObjectName("collapse_button")
        self.horizontalLayout.addWidget(self.collapse_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(Checklist)
        QtCore.QMetaObject.connectSlotsByName(Checklist)

    def retranslateUi(self, Checklist):
        _translate = QtCore.QCoreApplication.translate
        Checklist.setWindowTitle(_translate("Checklist", "Form"))
        self.checklist_label.setText(_translate("Checklist", "Checklist:"))
        self.tree.headerItem().setText(0, _translate("Checklist", "Tasks"))
        self.expand_button.setText(_translate("Checklist", "Expand Tasks"))
        self.collapse_button.setText(_translate("Checklist", "Collapse Tasks"))
