# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/current_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurrentWidget(object):
    def setupUi(self, CurrentWidget):
        CurrentWidget.setObjectName("CurrentWidget")
        CurrentWidget.resize(116, 279)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CurrentWidget.sizePolicy().hasHeightForWidth())
        CurrentWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(CurrentWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CurrentWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider = QtWidgets.QSlider(CurrentWidget)
        self.slider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 2px solid rgb(128, 192, 128);\n"
"    background: white;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: qlineargradient(x1: 0, y1: 0,   x2: 0, y2: 1, stop: 0 rgb(192, 255, 192), stop: 1 rgb(128, 192, 128));\n"
"    border: 4px solid rgba(128, 192, 128, 0);\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.slider.setOrientation(QtCore.Qt.Vertical)
        self.slider.setObjectName("slider")
        self.horizontalLayout_2.addWidget(self.slider)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(CurrentWidget)
        QtCore.QMetaObject.connectSlotsByName(CurrentWidget)

    def retranslateUi(self, CurrentWidget):
        _translate = QtCore.QCoreApplication.translate
        CurrentWidget.setWindowTitle(_translate("CurrentWidget", "CurrentWidget"))
        self.label.setText(_translate("CurrentWidget", "Device"))
