# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/tools_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tools(object):
    def setupUi(self, Tools):
        Tools.setObjectName("Tools")
        Tools.resize(879, 590)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Tools)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.antenna_control = AntennaControlWidget(Tools)
        self.antenna_control.setObjectName("antenna_control")
        self.gridLayout.addWidget(self.antenna_control, 1, 0, 1, 1)
        self.timer = TimerWidget(Tools)
        self.timer.setObjectName("timer")
        self.gridLayout.addWidget(self.timer, 0, 0, 1, 1)
        self.ros_console = RosConsoleWidget(Tools)
        self.ros_console.setObjectName("ros_console")
        self.gridLayout.addWidget(self.ros_console, 2, 0, 1, 1)
        self.checklist = ChecklistWidget(Tools)
        self.checklist.setObjectName("checklist")
        self.gridLayout.addWidget(self.checklist, 0, 1, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Tools)
        QtCore.QMetaObject.connectSlotsByName(Tools)

    def retranslateUi(self, Tools):
        _translate = QtCore.QCoreApplication.translate
        Tools.setWindowTitle(_translate("Tools", "Form"))
from heimdall_gui.urc_gui_common.widgets.antenna_control import AntennaControlWidget
from heimdall_gui.urc_gui_common.widgets.checklist import ChecklistWidget
from heimdall_gui.urc_gui_common.widgets.ros_console import RosConsoleWidget
from heimdall_gui.urc_gui_common.widgets.timer import TimerWidget
